PhotoApp/Models/Photo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public System.Guid AlbumId { get; set; }
        public byte[] Image { get; set; }
        public double Rating { get; set; }
        public int Views { get; set; }
        public string Name { get; set; }
        public System.Guid ImageId { get; set; }
    
        public virtual AlbumFolder AlbumFolder { get; set; }
    }
}

PhotoApp/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PhotoApp.Models;

namespace PhotoApp.Controllers
{
    public class AlbumController : Controller
    {
        //
        // GET: /Album/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListOfAlbums()
        {
            AlbumFolderModel a = new AlbumFolderModel();
            return PartialView(a.AlbumList(User.Identity.Name));
        }

        [HttpGet]
        public ActionResult NewAlbum()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewAlbum(AlbumFolder album)
        {
            var a = new AlbumFolderModel();
            Guid? albumIdent;
            try
            {
                albumIdent = a.NewAlbum(User.Identity.Name, album.AlbumTitle);
                if (albumIdent == null)
                    ModelState.AddModelError("", "Error");
                else
                {
                    return RedirectToAction("AlbumPhotos", "Photo", new { albumId = albumIdent });
                }

            }
            catch
            {
                ModelState.AddModelError("", "Wrong Data");
            }
            return View();
        }

        public ActionResult DeleteAlbum(Guid albumId)
        {
            if (new AlbumFolderModel().UserNameFromAlbumId(albumId) == User.Identity.Name)
            {
                new AlbumFolderModel().DeleteAlbum(albumId);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("UserLogin", "User");
            }
        }
    }
}

PhotoApp/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using PhotoApp.Models;

namespace PhotoApp.Controllers
{
    public class PhotoController : Controller
    {
        //
        // GET: /Photo/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RandomPhoto()
        {
            Photo[] model = new Photo[7];
            PhotoModel aa = new PhotoModel();

            for (int i = 0; i < 6; i++)
            {
                model[i] = aa.GetRandomPhoto(i);
            }

            return PartialView(model);
        }

        public ActionResult GenerateImage(int i)
        {
            PhotoModel aa = new PhotoModel();
            return new FileContentResult(aa.GetRandomPhoto(i).Image, "image/jpeg");
        }

        public ActionResult AlbumPhotos(Guid albumId)
        {
            if (new AlbumFolderModel().UserNameFromAlbumId(albumId) == User.Identity.Name)
            {
                Photo[] model = new Photo[100];
                PhotoModel aa = new PhotoModel();

                for (int i = 0; i < 100; i++)
                {
                    model[i] = aa.GetAlbumPhoto(i, albumId);
                    if (model[i] == null)
                    {
                        ViewBag.numberOfPhotosInAlbum = i;
                        ViewBag.albumId = albumId;
                        break;
                    }
                }
                return View(model);
            }
            else
            {
                return RedirectToAction("UserLogin", "User");
            }
        }

        public ActionResult GenerateAlbumImage(int i, Guid albumId)
        {
            if (new AlbumFolderModel().UserNameFromAlbumId(albumId) == User.Identity.Name)
            {
                return new FileContentResult(new PhotoModel().GetAlbumPhoto(i, albumId).Image, "image/jpeg");
            }
            return RedirectToAction("UserLogin", "User");
        }

        [HttpGet]
        public ActionResult AddingPhoto(Guid? albumId)
        {
            if (new AlbumFolderModel().UserNameFromAlbumId(albumId) == User.Identity.Name)
            {
                ViewBag.AlbumId = albumId;
                return View();
            }
            else
            {
                return RedirectToAction("UserLogin", "User");
            }
        }

        [HttpPost]
        public ActionResult AddingPhoto(HttpPostedFileBase[] photoFile, Photo photo)
        {
            for (int i = 0; i < 20; i++)
            {
                try
                {//end of the photos detected (foreach  don't work properly)
                    //here catch out of the bounds exception
                    var a = photoFile[i] != null;
                }
                catch (Exception)
                {
                    return RedirectToAction("AlbumPhotos", "Photo", new { albumId = photo.AlbumId });
                }
                if (photoFile[i] != null && photoFile[i].ContentLength > 0 && photo.Name != null && photo.Name.Length > 5 && photo.Name.Length < 100)
                {
                    try
                    {
                        if (!(new PhotoModel().AddPhoto(photoFile[i], photo)))
                        {
                            ModelState.AddModelError("", "Is it really an image?");
                            return RedirectToAction("AlbumPhotos", "Photo", new { albumId = photo.AlbumId });
                        }
                    }
                    catch
                    {
                        ModelState.AddModelError("", "An error when uploading");
                        return View(photo);
                    }
                }
                else
                {
                    ViewBag.albumId = photo.AlbumId;
                    if (photoFile[i] != null && photoFile[i].ContentLength > 0)
                        ModelState.AddModelError("", "Choose the correct name, please");
                    else
                        ModelState.AddModelError("", "Choose the correct image, please");
                    return View(photo);
                }
            }
            return RedirectToAction("AlbumPhotos", "Photo", new { albumId = photo.AlbumId });
        }

        public ActionResult DeletePhoto(Guid photoId)
        {
            if (new AlbumFolderModel().UserNameFromPhotoId(photoId) == User.Identity.Name)
            {

                new PhotoModel().DeletePhoto(photoId);
                return Redirect(Request.UrlReferrer.ToString());
            }
            else
            {
                return RedirectToAction("UserLogin", "User");
            }
        }
    }
}

PhotoApp/Views/Photo/AddingPhoto.cshtml
@model PhotoApp.Models.Photo

@{
    ViewBag.Title = "Adding Photo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddingPhoto</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="span4 offset4 well">
                <script src="~/Scripts/jquery-1.8.2.min.js"></script>
                <script src="~/Scripts/jquery.validate.min.js"></script>
                <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

                @using (Html.BeginForm("AddingPhoto", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "Something goes wrong")
    
                    <fieldset>
                        <legend>Photo</legend>
                        @Html.TextBoxFor(model => model.AlbumId, new { @Value = @ViewBag.AlbumId, @type = "hidden" })
                        <div class="editor-label">
                            @Html.LabelFor(model => model.Name)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.Name)
                            @Html.ValidationMessageFor(model => model.Name)
                        </div>
                        <input type="file" name="photoFile" multiple="multiply" />
                        <br />
                        <br />
                        <br />

                        <p>
                            <input type="submit" value="Create" />
                        </p>
                    </fieldset>
                }

            </div>
        </div>
    </div>
</body>
</html>

PhotoApp/Views/Photo/AlbumPhotos.cshtml
@model PhotoApp.Models.Photo[]

@{
    ViewBag.Title = "AlbumPhotos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (ViewBag.numberOfPhotosInAlbum > 0)
{
    <!-- Main Area -->
    <div id="main_area">
        <!-- Slider -->
        <div class="row">
            <div class="span12" id="slider">
                <!-- Top part of the slider -->
                <div class="row">
                    <div class="span8" id="carousel-bounding-box">
                        <div id="myCarousel" class="carousel slide">
                            <!-- Carousel items -->

                            <div class="carousel-inner">
                                <div class="active item" data-slide-number="0">
                                    <img src="@Url.Action("GenerateAlbumImage", "Photo", new { i = 0, albumId = ViewBag.albumId }, null)" alt="Random 0" width ="700" height="500"/>
                                </div>
                                @for (int i = 1; i < ViewBag.numberOfPhotosInAlbum; i++)
                                {
                                    <div class="item" data-slide-number="@i">
                                        <img src="@Url.Action("GenerateAlbumImage", "Photo", new { i = @i, albumId = ViewBag.albumId }, null)" alt="Random @i"  width ="700" height="500"/>
                                    </div>
                                }

                            </div>

                            <!-- Carousel nav -->
                            <a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a>
                            <a class="carousel-control right" href="#myCarousel" data-slide="next">›</a>
                        </div>
                    </div>
                    <div class="span4" id="carousel-text"></div>

                    <div style="display: none;" id="slide-content">
                        @for (int i = 0; i < ViewBag.numberOfPhotosInAlbum; i++)
                        {
                            <div id="slide-content-@i">
                                <h2>From @Model[@i].AlbumFolder.AlbumTitle album</h2>
                                <p>@Model[@i].Name</p>
                                <p class="sub-text">Published by @Model[@i].AlbumFolder.User.Name</p>
                                <p>@Html.ActionLink("Delete Photo", "DeletePhoto", "Photo", new { photoId = Model[@i].ImageId }, null)</p>
                                <p>Current rating: @Model[@i].Rating</p>
                                @*//==========================================================*@


                                <p>
                                    <img src="../../Content/Images/EmptyStar.png" alt="Star Rating" id="star+1+@Model[@i].ImageId" height="15" width="15"/>
                                    <img src="../../Content/Images/EmptyStar.png" alt="Star Rating" id="star+2+@Model[@i].ImageId" height="15" width="15"/>
                                    <img src="../../Content/Images/EmptyStar.png" alt="Star Rating" id="star+3+@Model[@i].ImageId" height="15" width="15"/>
                                    <img src="../../Content/Images/EmptyStar.png" alt="Star Rating" id="star+4+@Model[@i].ImageId" height="15" width="15"/>
                                    <img src="../../Content/Images/EmptyStar.png" alt="Star Rating" id="star+5+@Model[@i].ImageId" height="15" width="15"/>
                                </p>
                                <div id="result"></div>
                                @*    //==========================================================       *@

                                <script language="javascript" type="text/javascript" src="../../Scripts/jquery-1.9.1.js"></script>
                                <script language="javascript" type="text/javascript">
                                    $(function () {
                                        $('[id^=star]').mouseover(function () {
                                            giveRating($(this), "FilledStar.png");
                                            $(this).css("cursor", "pointer");
                                        });

                                        $('[id^=star]').mouseout(function () {
                                            giveRating($(this), "EmptyStar.png");
                                        });

                                        $('[id^=star]').click(function () {
                                            $('[id^=star]').unbind("mouseout mouseover click");

                                            // call ajax methods to update database
                                            var id_selector = $(this).attr("id");
                                            var n = id_selector.split("+");

                                            var url = "/Rating/PostRating?rating=" + n[1] + "&imageId=" + n[2];
                                            $.post(url, null, function (data) {
                                                $("#result").text(data);
                                            });
                                        });
                                    });

                                    function giveRating(img, image) {
                                        img.attr("src", "/Content/Images/" + image)
                                           .prevAll('[id^=star]').attr("src", "/Content/Images/" + image);
                                    }
                                </script>
                            </div>
                            
                        }
                    </div>
                </div>

            </div>
        </div>
        <!--/Slider-->

        <div class="row hidden-phone" id="slider-thumbs">
            <div class="span12">
                <!-- Bottom switcher of slider -->
                <ul class="thumbnails">
                    @for (int i = 0; i < ViewBag.numberOfPhotosInAlbum; i++)
                    {
                        <li class="span2">
                            <a class="thumbnail" id="carousel-selector-@i">
                                <img src="@Url.Action("GenerateAlbumImage", "Photo", new { i = @i, albumId = ViewBag.albumId }, null)"  width ="170" height="100"/>
                            </a>
                        </li>
                    }
                    <li class="span2">
                        <a class="thumbnail" id="carousel-selector-100">
                            @Html.ActionLink("Add Photo", "AddingPhoto", "Photo", new { albumId = ViewBag.albumId }, null)
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script>
        jQuery(document).ready(function ($) {

            $('#myCarousel').carousel({
                interval: 5000
            });

            $('#carousel-text').html($('#slide-content-0').html());

            //Handles the carousel thumbnails
            $('[id^=carousel-selector-]').click(function () {
                var id_selector = $(this).attr("id");
                var id = id_selector.substr(id_selector.lastIndexOf("-") + 1);
                var id = parseInt(id);
                $('#myCarousel').carousel(id);
            });


            // When the carousel slides, auto update the text
            $('#myCarousel').on('slid', function (e) {
                var id = $('.item.active').data('slide-number');
                $('#carousel-text').html($('#slide-content-' + id).html());
            });

            // keyboard left and right arrow navigation

            $(document.documentElement).keyup(function (event) {
                if (event.keyCode === 37) {
                    // click prev
                    $("#slider a.carousel-control[data-slide='prev']").click();
                } else if (event.keyCode === 39) {
                    // click next
                    $("#slider a.carousel-control[data-slide='next']").click();
                }
            });

        });
    </script>
}
else
{
    <h2>Hm. You have no photos there.</h2>
    @Html.ActionLink("Add Photo", "AddingPhoto", "Photo", new { albumId = ViewBag.albumId }, null)
    <br />
    @Html.ActionLink("Delete Album", "DeleteAlbum", "Album", new { albumId = ViewBag.albumId }, null)
}

PhotoApp/Views/Photo/DeletePhoto.cshtml
@{
    ViewBag.Title = "DeletePhoto";
}

<h2>This photo has been deleted.</h2>

PhotoApp/Views/Photo/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ЙУХУ!!! слишком большая фотка</h2>
<img src="http://miranimashek.com/_ph/239/2/67315806.jpg" />

PhotoApp/Views/Photo/RandomPhoto.cshtml
@model PhotoApp.Models.Photo[]

<!-- Main Area -->
<div id="main_area">
    <!-- Slider -->
    <div class="row">
        <div class="span12" id="slider">
            <!-- Top part of the slider -->
            <div class="row">
                <div class="span8" id="carousel-bounding-box">
                    <div id="myCarousel" class="carousel slide">
                        <!-- Carousel items -->
                        <div class="carousel-inner">
                            <div class="active item" data-slide-number="0">
                                <img src="@Url.Action("GenerateImage", "Photo", new { i = 0 }, null)" alt="Random 0" width ="700" height="500"/>
                            </div>
                            @for (int i = 1; i < 6; i++)
                            {

                                <div class="item" data-slide-number="@i">
                                    <img src="@Url.Action("GenerateImage", "Photo", new { i = @i }, null)" alt="Random @i" width ="700" height="500"/>
                                </div>
                            }

                        </div>
                        <!-- Carousel nav -->
                        <a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a>
                        <a class="carousel-control right" href="#myCarousel" data-slide="next">›</a>
                    </div>
                </div>
                <div class="span4" id="carousel-text"></div>

                <div style="display: none;" id="slide-content">
                    @for (int i = 0; i < 6; i++)
                    {
                        <div id="slide-content-@i">
                            <h2>From @Model[@i].AlbumFolder.AlbumTitle album</h2>
                            <p>@Model[@i].Name</p>
                            <p class="sub-text">Published by @Model[@i].AlbumFolder.User.Name</p>
                            <p>Current rating: @Model[@i].Rating</p>
                        </div>
                    }
                </div>
            </div>

        </div>
    </div>
    <!--/Slider-->

    <div class="row hidden-phone" id="slider-thumbs">
        <div class="span12">
            <!-- Bottom switcher of slider -->
            <ul class="thumbnails">
                @for (int i = 0; i < 6; i++)
                {

                    <li class="span2">
                        <a class="thumbnail" id="carousel-selector-@i">
                            <img src="@Url.Action("GenerateImage", "Photo", new { i = @i }, null)" alt="Random @i"  width ="170" height="100"/>
                        </a>
                    </li>
                }

            </ul>
        </div>
    </div>
</div>
<script>
    jQuery(document).ready(function ($) {

        $('#myCarousel').carousel({
            interval: 5000
        });

        $('#carousel-text').html($('#slide-content-0').html());

        //Handles the carousel thumbnails
        $('[id^=carousel-selector-]').click(function () {
            var id_selector = $(this).attr("id");
            var id = id_selector.substr(id_selector.lastIndexOf("-") + 1);
            var id = parseInt(id);
            $('#myCarousel').carousel(id);
        });


        // When the carousel slides, auto update the text
        $('#myCarousel').on('slid', function (e) {
            var id = $('.item.active').data('slide-number');
            $('#carousel-text').html($('#slide-content-' + id).html());
        });

        // keyboard left and right arrow navigation

        $(document.documentElement).keyup(function (event) {
            if (event.keyCode === 37) {
                // click prev
                $("#slider a.carousel-control[data-slide='prev']").click();
            } else if (event.keyCode === 39) {
                // click next
                $("#slider a.carousel-control[data-slide='next']").click();
            }
        });

    });
</script>