PhotoApp/Models/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AlbumFolders = new HashSet<AlbumFolder>();
        }
    
        public System.Guid UserId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<AlbumFolder> AlbumFolders { get; set; }
        public virtual Right Right { get; set; }
    }
}

PhotoApp/Controllers/UserController.cs
using System.Drawing.Imaging;
using PhotoApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PhotoApp.Tools;

namespace PhotoApp.Controllers
{
    public class UserController : Controller
    {
        //
        // GET: /User/

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult UserLogin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UserLogin(UserModel user)
        {
            if (ModelState.IsValid)
            {//if transmitted data is correct
                if (user.IsValid())
                {//set cookie
                    FormsAuthentication.SetAuthCookie(user.Name, false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Login Data is incorrect.");
                }
            }
            return View(user);
        }

        [HttpGet]
        public ActionResult UserRegister()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UserRegister(UserModelRegistration user)
        {
            if (user.Captcha != (string)Session[CaptchaImage.CaptchaValueKey])
            {
                ModelState.AddModelError("", "Try again with the captcha");
                return View(user);
            }

            if (ModelState.IsValid)
            {
                if (!user.Register())
                {
                    ModelState.AddModelError("", "We have this user, sorry");
                    return View(user);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ModelState.AddModelError("", "login data is incorrect");
            }
            return View(user);
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Captcha()
        {
            Session[CaptchaImage.CaptchaValueKey] = new Random(DateTime.Now.Millisecond).Next(1111, 9999).ToString();
            var ci = new CaptchaImage(Session[CaptchaImage.CaptchaValueKey].ToString(), 211, 50, "Arial");

            this.Response.Clear(); // Change the response headers to output a JPEG image.
            this.Response.ContentType = "image/jpeg";

            // Write the image to the response stream in JPEG format.
            ci.Image.Save(this.Response.OutputStream, ImageFormat.Jpeg);

            ci.Dispose(); // Dispose of the CAPTCHA image object.
            return null;
        }

    }
}

PhotoApp/Views/User/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

PhotoApp/Views/User/UserLogin.cshtml
@model PhotoApp.Models.UserModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "UserLogin";
}

@using (Html.BeginForm())
{
    <div class="container">
        <div class="row">
            <div class="span4 offset4 well">
                <fieldset>
                    <legend>Login Form</legend>

                    <div>@Html.LabelFor(u => u.Name)</div>
                    <div>@Html.TextBoxFor(u => u.Name)
                        @Html.ValidationMessageFor(u => u.Name)
                    </div>

                    <div>@Html.LabelFor(u => u.Password)</div>
                    <div>@Html.PasswordFor(u => u.Password)
                        @Html.ValidationMessageFor(u => u.Password)
                    </div>

                    <input type="submit" value="Log In" />
                </fieldset>
            </div>

        </div>
    </div>
}

PhotoApp/Views/User/UserRegister.cshtml
@model PhotoApp.Models.UserModelRegistration
@{
    ViewBag.Title = "Registration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Registration
    {
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true, "Wrong Create Information")

        <div class="container">
            <div class="row">
                <div class="span4 offset4 well">
                    <fieldset>
                        <legend>Create new User</legend>

                        <div class="editor-label">@Html.LabelFor(u => u.Name)</div>
                        <div class="editor-field">@Html.TextBoxFor(u => u.Name)
                            @Html.ValidationMessageFor(u => u.Name)
                        </div>

                        <div class="editor-label">@Html.LabelFor(u => u.Password)</div>
                        <div class="editor-field">@Html.PasswordFor(u => u.Password)
                            @Html.ValidationMessageFor(u => u.Password)
                        </div>
                        <label class="control-label">
                            <img src="@Url.Action("Captcha", "User")" alt="captcha" />
                        </label>
                        <div class="editor-label">@Html.LabelFor(u => u.Captcha)</div>
                        <div class="editor-field">@Html.TextBoxFor(u => u.Captcha)
                            @Html.ValidationMessageFor(u => u.Captcha)
                        </div>
                        <input type="submit" value="Register" />
                    </fieldset>
                </div>
            </div>
        </div>
    }
}